steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', '${_ARTIFACT_REGISTRY_URL}/static-frontend:${SHORT_SHA}',
        'frontend'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_ARTIFACT_REGISTRY_URL}/static-frontend:${SHORT_SHA}'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'static-frontend',
        '--image', '${_ARTIFACT_REGISTRY_URL}/static-frontend:${SHORT_SHA}',
        '--platform', 'managed',
        '--region', 'europe-west3',
        '--allow-unauthenticated',
        '--port', '80'
      ]

images:
  - '${_ARTIFACT_REGISTRY_URL}/static-frontend:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
