steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build', '-t', '${_ARTIFACT_REGISTRY_URL}/static-frontend:${SHORT_SHA}', '.'
      ]

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push', '${_ARTIFACT_REGISTRY_URL}/static-frontend:${SHORT_SHA}'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'static-frontend',
        '--image', '${_ARTIFACT_REGISTRY_URL}/static-frontend:${SHORT_SHA}',
        '--platform', 'managed',
        '--region', 'europe-west3',
        '--allow-unauthenticated',
        '--port', '80'
      ]

images:
  - '${_ARTIFACT_REGISTRY_URL}/static-frontend:${SHORT_SHA}'
